#!/bin/sh

PORT=1010
VERSION=1.0.3-SNAPSHOT
SERVER_NAME=snowflake-server
JAR_NAME=${SERVER_NAME}-${VERSION}.jar
EXEC=${JAR_NAME}

PIDFILE=${SERVER_NAME}-${PORT}.pid

case "$1" in
    st)
        echo "Starting wms server..."
        nohup java -jar -Dfile.encoding=UTF-8 $EXEC --server.port=${PORT} > /dev/null & echo $! > $PIDFILE
        ;;
    sp)
        if [ ! -f $PIDFILE ]
        then
                echo "$PIDFILE does not exist, process is not running"
        else
                kill $(cat ${SERVER_NAME}-1010.pid)
                echo "wms server stopped"
        fi
        ;;
    ss)
        ps -ef|grep ${JAR_NAME}
        ;;
    lg)
        tail -f _logs/spring.log
        ;;
    rt)
        "$0" stop
        sleep 3
        "$0" start
        ;;
    *)
        echo "Please use start or stop or restart as first argument"
        ;;
esac
